version: 3
projects:
- name: security
  dir: security
  terraform_version: v1.8.1
  branch: /main/
  workflow: makeworkflow
  autoplan:
    when_modified:
      - '../modules/**/*.tf'
      - '../modules/**/*.sh'
      - '../modules/**/*.json'
      - '.terraform.lock.hcl'
      - '*.tfvars'
      - '../atlantis-security.yaml'
    enabled: true
  apply_requirements: [mergeable, approved]
workflow:
  makeworkflow:
    plan:
      steps:
        - run: make clean_state init plan
    apply:
      steps:
        - run: make init apply
    import:
      steps:
        - run: rm -rf .terraform terraform.tfstate*
