services:
  ngrok:
    image: ngrok/ngrok
    ports:
      - 4040:4040
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: http atlantis:4141
  atlantis:
    image: ghcr.io/runatlantis/atlantis
    ports:
      - 4141:4141
    environment:
      AWS_CONFIG_FILE: '/home/atlantis/.aws/config'
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_DEFAULT_REGION: 'us-east-1'
      DEFAULT_CONFTEST_VERSION: ${DEFAULT_CONFTEST_VERSION}
      ATLANTIS_ATLANTIS_URL: ${ATLANTIS_ATLANTIS_URL}
      ATLANTIS_GH_USER: ${ATLANTIS_GH_USER}
      ATLANTIS_GH_TOKEN: ${ATLANTIS_GH_TOKEN}
      ATLANTIS_GH_WEBHOOK_SECRET: ${ATLANTIS_GH_WEBHOOK_SECRET}
      ATLANTIS_REPO_ALLOWLIST: ${ATLANTIS_REPO_ALLOWLIST}
      ATLANTIS_REPO_CONFIG: ${ATLANTIS_REPO_CONFIG}
      ATLANTIS_HIDE_PREV_PLAN_COMMENTS: true
      ATLANTIS_EMOJI_REACTION: eyes
    volumes:
      - ~/.aws:/home/atlantis/.aws:ro
      - $PWD/repos.yaml:$HOME/repos.yaml