repos:
  - id: /.*/
    workflow: makeworkflow
    apply_requirements: [approved, mergeable]
    allowed_overrides: [apply_requirements, workflow]
    allow_custom_workflows: true
    pre_workflow_hooks:
      - run: "cat /config/atlantis.yaml > atlantis.yaml"
workflows:
  makeworkflow:
    plan:
      steps:
        - run: make clean-state atlantis-init atlantis-plan
    apply:
      steps:
        - run: make atlantis-init atlantis-apply